name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: "Bug Report"
body:
  - type: textarea
    id: explanation
    attributes:
      label: Bug Explanation
      description: What is the bug, and what did you expect to happen?
      placeholder: e.g. The TensorFlow frontend is missing instance methods.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce bug
      description: Explain how to reproduce the bug.
      placeholder: "e.g. Run the following code:"
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: What environment did you encounter the bug in?
      placeholder: e.g. Windows 11 using PyCharm CE & Docker.
    validations:
      required: false